### ISSUE TITLE
[RFC] What would be most valuable for Informal Systems?

### ISSUE THREAD

**Issue by JonathanLorimer** [informalsystems/cosmos.nix#14]
Now that all the packages are at least in PR (only tendermint-rs is proving difficult) I am wondering what the greatest value-add besides reproducible builds would be. I think there are a couple nice things that we can get from nix, but its unclear which ones I should prioritize, here are a couple suggestions:

- **Integration Tests:** [NixOS Testing Library](https://nixos.wiki/wiki/NixOS_Testing_library) is a pretty cool project that makes it easy to write integration tests using `qemu` virtualization. This seems like a great fit for integration testing relayers using `gaia` to spin up a couple local chains. You can find a nice article on integration testing with VM's using NixOS Testing Library [here](https://nix.dev/tutorials/integration-testing-using-virtual-machines)
- **Docker Images**: [Nix Docker Tools](https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-dockerTools) provide a really nice way to generate docker images from nix derivations. You get the reproducibility of nix (for the software that you are providing via nix) and you can provide it to devs in the familiar docker format. There could be an image per package, or a single image providing all of them, or a collection of packages that make sense to provide in concert, I would have to talk to someone about what makes the most sense. You can find a nice article on creating docker images with nix [here](https://nix.dev/tutorials/building-and-running-docker-images)
- **AMI's**: Nix makes it really easy to bake software into AWS ami's, using AWS kind of feels wrong given the values of this community, but its an option if you think it would be useful for relayers!
- **Development Environments**: This one doesn't follow from as clearly from the packaging work that has been happening in this repo, but it might be useful to informal to be able to provide consistent, 1 command development environments for developers at informal. I would be happy to build some of those nix shells in this repo, and then whoever wants to use them could clone the repo and enter a nix shell from there!

If you can think of some other way that we can start making this repo useful, please comment!

**Comment by soareschen** [comment]
Thanks for the initiative! I think the most valuable feature we can deliver is to use Nix for end-to-end testing. I have described it in more details in #15. 

As of now, the best tools we have is [Gaia Manager](https://github.com/informalsystems/ibc-rs/tree/master/scripts/gm) and the [dev-env](https://github.com/informalsystems/ibc-rs/blob/master/scripts/dev-env) scripts, which provide pretty basic functionality in managing test chains. We can potentially write Nix modules that have the same features, but most importantly they need to be as intuitive to use as the current tools so that users are willing to adopt Nix.

For us to officially adopt Nix for end-to-end testing, we will have to convince the others that the solution offered by Nix is much better than alternatives like Docker or even plain Bash. Ideally users should only need to install Nix on a fresh machine and be able to run all end-to-end tests from the get go.

It is also important that users are able to write new chain configurations to be used by the end-to-end tests. It can potentially be challenging if users need to learn the Nix language to edit the configuration. We may also want to investigate whether users can edit the configuration in simpler languages like JSON, YAML, or TOML.

**Comment by JonathanLorimer** [comment]
@soareschen I seem to remember that informal configures some of their legal contracts with dhall? Perhaps this tool https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-nix would provide an easier interface for configuration?

**Comment by soareschen** [comment]
The use of Dhall was experimental, and I'm not sure there is widespread use of it yet. A potential issue for Dhall is that the learning curve is still pretty steep, and support for features like recursive types are limited. We may want to try out simpler solutions like YAML first, and then consider switching to more advanced languages like Dhall or Nix when the need arise to configure complicated setups.

**Comment by JonathanLorimer** [comment]
It seems that end to end testing is the initial priority. Closing by https://github.com/informalsystems/cosmos.nix/issues/15.
