### ISSUE TITLE
End-to-end testing in Nix

### ISSUE THREAD

**Issue by soareschen** [informalsystems/cosmos.nix#15]
One of the strength of Nix is that users are able to deploy services like Nginx and web applications all using Nix expressions. For the case of end-to-end testing, we want to be able to deploy multiple chains with specific configurations and running on different ports. This could be potentially be solved using NixOps, by creating modular Nix modules that allow users to specify the chain configurations they want to deploy.

For example, the user should be use Nix do deploy a chain configuration like:

- One chain running with Gaia v5.0 with 2 validators at ports 27000 and 27001.
- One chain running with Gaia v4.2 with 1 validator at port 27003.

The deployment should also allow user to specify specific key pairs during deployment, or let the deployment automatically generate key pairs during initial setup. It is fine to not be extra careful with the private keys in this case, as we only need them for testing on test chains.

It would also be nice if the deployment can be done through Docker instead of NixOps, to make it easier for adoption by non-Nix users.

We should be able to configure similar deployment configurations as in the example [Gaia Manager config](https://github.com/informalsystems/ibc-rs/blob/master/scripts/gm/gm.toml), other than the configuration is done in Nix.

**Comment by JonathanLorimer** [comment]
A couple of points here:
- I think it would be good to use NixOS Testing Library for some integration testing automation
- I 100% agree about have some sort of `cosmosTools` or `chainTools` that provide an abstraction over deploying chains
- I am sure you are aware that nix has a bit of a hard time with secrets being leaked in the nix store. I have done some work with sops-nix and have recently been investigating a nix integration with hashicorps' `vault` so this could be a solution to the secrets problem

I have an ask:
- Is there some sort of spec about the parameters for configuring a gaia chain / hermes relayer? I can probably deduce them from reading the docs, the code, and the gaia manager config linked, but if the document already exists that would definitely help expedite things!

**Comment by soareschen** [comment]
> I think it would be good to use NixOS Testing Library for some integration testing automation. We can still provide abstractions for easy deployments to aid in manual testing, or for easy access from a test harness, but the virtualization and automation NixOS tests provide is ready out of the box.

I am not familiar with the NixOS Testing Library, and I don't find much documentation about it. It may be nice to use that if there are good documentation out there. Otherwise it might also be simpler to write our own testing tools for the specific use case.

> I am sure you are aware that nix has a bit of a hard time with secrets being leaked in the nix store. I have done some work with sops-nix and have recently been investigating a nix integration with hashicorps' vault so this could be a solution to the secrets problem.

I think It is fine to not worry about production use cases for now. In practice, validators use hardware solutions like HSM and on-premise hosting to ensure that the private keys never leak. So the private key files are mainly used only for testing purposes. I think the secret management in Nix is too complicated to worry for now. As long as we properly label warnings that it is only for testing purpose, it should be fine even when private keys are leaked.

> Is there some sort of spec about the parameters for configuring a gaia chain / hermes relayer?

We are still trying to figure out what kind of configurations do users want. I think the most common cases are parameters like:

- Number of chains and their names
- Number of validators and their names
- Number of users and their names

Once configured, the user should be able to enter a Nix shell with environment variables for the generated parameters like generated key paths. They should also be able to start and stop individual chains and validators for testing purposes.

**Comment by JonathanLorimer** [comment]
Would we want to run these chains on the same machine, or spin up some virtualization? Both options are possible!

**Comment by soareschen** [comment]
> Would we want to run these chains on the same machine, or spin up some virtualization, or even be able to run the tests on a remote host?

The end-to-end tests will be running on local developer machines as well as CI. So it is best to run all chains on one machine/container. Part of the appeal for the Gaia Manager solution is also that users do not have to have complicated Docker cluster setup. So Nix also shines in the same way in addition to managing the compiled binaries.

Another important aspect is that users should be able to enter the Nix shell or local container and interact with the spawned chains manually. This is needed for troubleshooting the tests when things are broken. They should be able to do the same things as the test scripts via shell. Some example commands I can think of:

- `systemctl start test-chain-a` 
  - The downside of using `systemctl` is that users would not able to use it in a plain Nix shell and instead have to have a full buy-in of NixOps or containers
- `supervisorctl start test-chain-a` 
  - The advantage of using something like `supervisord` is that users do not need to install Docker, Virtualbox, or Qemu to run the tests. 
  - The disadvantage is that Nix do not have integration with `supervisord`, and the spawned chains may encounter errors when binding to local ports on the user machine.
  - The Nix environment of services managed by supervisor do not get refreshed when the Nix code is updated. Instead users will have to kill supervisor manually and start it again in a new Nix shell.
- `hermes -c $HERMES_CONFIG start` - Environment variables like `$HERMES_CONFIG` are set by Nix shell with the configuration for the test chains.

I'm not sure if any of the libraries you stated are able to provide such flexibility. But it is worth exploring them as well.

And sorry for the random list of ideas. I'm just thinking out loud what features could be provided by Nix for end-to-end tests. They are not set in stone and we would have to find suitable solutions as the work continues.

**Comment by JonathanLorimer** [comment]
> And sorry for the random list of ideas. I'm just thinking out loud what features could be provided by Nix for end-to-end tests. They are not set in stone and we would have to find suitable solutions as the work continues.

No worries, I think this conversation has already been productive in identifying some key goals.

> The advantage of using something like supervisord is that users do not need to install Docker, Virtualbox, or Qemu to run the tests.

Is this that big of a concern, if we are using nix to provide everything (either directly via nix integrated testing tool or indirectly via the nix shell)?

Here are a couple ideas:
- I found this project [disnix](https://github.com/svanderburg/disnix) I would have to read through it more, but it might provide inroads
- I could write a nix wrapper for interacting with `supervisord`, this would be useful to the nix community and informal, but seems like a large undertaking.
- I wonder if some of this could be controlled by a test framework that lets you step through the tests, or runs the tests until failure and then preserves the environment for inspection rather than winding down? I am not sure what kind of support gaia has for rolling back and action, but that might be useful.

I will probably try to take some time over the next few days to research some of the existing options in the nix ecosystem in greater depth. But I would like to outline some high level goals for the project:
- Local first workflow (either using virtualization or process management)
- Minimal dev setup (this can be facilitated by removing installation steps and providing software via nix, also by controlling environments using nix shell)
- Mid-test state inspection
- Ergonomic state configuration (probably not nix!)

Let me know if I missed anything

**Comment by JonathanLorimer** [comment]
Quick Update:

From my brief investigation it looks like `Docker` is probably the correct tool. It has the advantage of running easily on both mac and linux and we could eventually get startup to be a one liner that requires no nix knowledge `docker load < $(nix-build hello-docker.nix)`.

One of the questions that arises is whether we want to run multiple chains within one container, or open up ports on the containers and have a container per chain. The single container option is easier to configure; different chain configurations would just be some sort of automation tool like the existing scripts. The multi container option is interesting because it is better at emulating the distributed nature of Cosmos, we could use `docker-compose` and [arion](https://docs.hercules-ci.com/arion/) to manage this "multi container application".

Configuration is a bit tricky, but the nix makes it easy to generate different docker images. I am imagining a bunch of different UI's for generating these images: config file that gets passed to nix, CLI, or even a web GUI. Then it is up to the developer to run their test harness against the docker images (Either within them, or calling the exposed ports).

**Comment by soareschen** [comment]
> One of the questions that arises is whether we want to run multiple chains within one container, or open up ports on the containers and have a container per chain.

I think it would be good to have everything to run in one container, including the end-to-end tests. Otherwise it would require users to know about docker-compose to be able to modify and run the tests. There is also no extra benefits to use multi-container at this stage, but we may consider them again in the future when the need arise.

> Configuration is a bit tricky, but the nix makes it easy to generate different docker images.

Indeed configuration is a bit tricky. We can probably think about setting up a container with all possible blockchain programs installed in it, then only think about how to make it easy to launch those programs with different configurations later on.

Btw I remember a major pain point of using a single Docker container is that there is poor support for multi-process management and zombie process pruning. They do not even support service managers like systemd inside the containers. The single-process philosophy of Docker makes it significantly more challenging to setup a multi-process environment like the E2E tests we want. I am reluctant to use solutions like Docker Compose for the sole reason being a workaround of the single-process limitation of Docker. So we may want to take this into consideration for using Docker for the E2E testing setup.

**Comment by JonathanLorimer** [comment]
If that's the case I would love to just use `systemd-nspawn` containers, nix has really great support for those out of the box! The primary concern then is how to support MacOS. I know Docker does some virtualization under the hood to make it _seem_ like you are just running docker on your mac, I wonder if we could provide a tool for that, `vagrant` comes to mind.

**Comment by JonathanLorimer** [comment]
Another option that comes to mind is just writing a Haskell program that does the same thing as `gm`. I feel like the functionality of gm has grown beyond regular bash scripts. We can provide all the dependencies via the nix-shell and users can provide configuration with `toml` files, although I think it would be _really_ nice to have a statically typed configuration language so that we can provide type bindings. A possible solution is to have the Haskell program read in a `json` or `yaml` file and also provide type bindings for dhall and then use `dhall-to-json` or `dhall-to-yaml`. Unfortunately `dhall-to-toml` is a WIP right now.

**Comment by soareschen** [comment]
> If that's the case I would love to just use `systemd-nspawn` containers, nix has really great support for those out of the box!

That might work if Nix already has good support and does not require additional user setup on Linux. I think the users might resist adoption if they need to learn how to use `systemd-nspawn`. Otherwise if it works transparently without them aware of it, then it might be worth trying out.

> The primary concern then is how to support MacOS.

Supporting Mac is indeed painful, and since we have limited manpower, we may want to leave Mac unsupported for now. A possible alternative with least resistance is that we can integrate with [GitHub Codespaces](https://github.com/features/codespaces) so that developers on Mac and Windows machines can easily run anything through a Codespaces instance.

> Another option that comes to mind is just writing a robust cli program that does the same thing as gm.

That is something I'd like to see, although it is currently not a priority for the team to build that. Having a `gm` alternative also requires good documentation and have users to relearn how to do things using the new program. So I think packaging `gm` is the fastest way we can give users a quick taste of Nix with any existing workflow they already have.

**Comment by JonathanLorimer** [comment]
Crypto.com uses nix to create an environment for their E2E tests, and just has some python automation to run the tests. I might take some cues from that. https://github.com/crypto-org-chain/chain-main/blob/master/default.nix

**Comment by JonathanLorimer** [comment]
Base on this [comment](https://github.com/informalsystems/cosmos.nix/pull/51#pullrequestreview-914213094) I think it is fair to say that cosmos.nix will play a supporting role in E2E testing, with the majority of the testing logic living in [ibc-rs](https://github.com/informalsystems/ibc-rs)
