### ISSUE TITLE
Package Major Cosmos-SDK-based Blockchain projects

### ISSUE THREAD

**Issue by soareschen** [informalsystems/cosmos.nix#19]
There are many blockchain projects that are derived from cosmos-sdk and work similarly to Gaia. We should include them in Nix for end-to-end testing.

A non-comprehensive list:

- [Osmosis](https://github.com/osmosis-labs/osmosis)
- [Terra](https://github.com/terra-money/core)
- [Regen](https://github.com/regen-network/regen-ledger)
- [Akash](https://github.com/ovrclk/akash)
- [Thor](https://github.com/thorchain/thornode)

**Comment by JonathanLorimer** [comment]
Some potential additions would be:
- [Gravity Dex](https://github.com/b-harvest/gravity-dex-backend)
- [Aragon Chain](https://github.com/aragon/aragon-chain)
- [Sentinel Hub](https://github.com/sentinel-official/hub)
- [F-O-A-M](https://github.com/f-o-a-m) (I am not sure where their chain implementation lives)
- [Iris Hub](https://github.com/irisnet/irishub)

**Comment by JonathanLorimer** [comment]
Both [sentinel](https://github.com/informalsystems/cosmos.nix/pull/41) and [akash](https://github.com/informalsystems/cosmos.nix/pull/42) are failing on `syncGoModules`. Something is up with their dependencies, and I think it is a transitive dependency since I manually verified the explicit dependencies in `go.mod`. I will need to improve my understanding of the actual go code in `gomod2nix` to resolve this one!

**Comment by JonathanLorimer** [comment]
A lot has changed since this issue has been opened. Here are a list of the projects that remain to be packaged:
- Terra
- Juno
- Sentinel
- Akash
- Thor

**Comment by JonathanLorimer** [comment]
I think we are close enough on this one, will add chains as I can!
